### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by Topxue** [sxzz/unplugin-vue-jsx#1]
Vue版本2.7.0

使用 require('unplugin-vue-jsx/webpack')() 得到错误TypeError: require(...) is not a function

使用代码如下
![image](https://user-images.githubusercontent.com/38459200/178443483-43dbf247-4b9f-43dd-99ab-f46a1776b0bb.png)
错误信息
![image](https://user-images.githubusercontent.com/38459200/178443845-a4c47ac2-9f9b-42ca-ab48-ee9f324c8bbf.png)

**Comment by sxzz** [comment]
Try 0.1.1
